### ISSUE TITLE
python manage.py runserver error

### ISSUE THREAD

**Issue by LihengGong** [fanout/headline#2]
Django==1.7.1
PyJWT==0.4.3
argparse==1.2.1
dj-database-url==0.3.0
dj-static==0.0.6
django-grip==1.6.1
django-toolbelt==0.0.1
gripcontrol==2.4.1
gunicorn==19.1.1
***psycopg2==2.7.5***
pubcontrol==2.2.6
requests==2.7.0
static3==0.5.1

(venv) ➜  headline git:(master) ✗ python manage.py runserver
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/gongliheng/Documents/fanout/headline/headline/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/gongliheng/Documents/fanout/headline/headline/venv/lib/python3.6/site-packages/django/core/management/__init__.py", line 345, in execute
    settings.INSTALLED_APPS
  File "/Users/gongliheng/Documents/fanout/headline/headline/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 46, in __getattr__
    self._setup(name)
  File "/Users/gongliheng/Documents/fanout/headline/headline/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 42, in _setup
    self._wrapped = Settings(settings_module)
  File "/Users/gongliheng/Documents/fanout/headline/headline/venv/lib/python3.6/site-packages/django/conf/__init__.py", line 94, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/Users/gongliheng/Documents/fanout/headline/headline/venv/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/gongliheng/Documents/fanout/headline/headline/headline/settings.py", line 109, in <module>
    GRIP_PROXIES = [parse_grip_uri(os.environ['GRIP_URL'])]
  File "/Users/gongliheng/Documents/fanout/headline/headline/venv/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'GRIP_URL'

**Comment by LihengGong** [comment]
Code can run now.
Thanks for the updating and quick response.

headline git:(master) ✗ curl -X POST http://localhost:8000
{
    "id": "1",
    "type": "none",
    "date": "2018-07-14T19:48:55.159144+00:00",
    "text": ""
}
➜  headline git:(master) ✗ curl -X POST http://localhost:8000
{
    "id": "2",
    "type": "none",
    "date": "2018-07-14T19:49:04.373151+00:00",
    "text": ""
}
➜  headline git:(master) ✗ curl -X POST http://localhost:8000
{
    "id": "3",
    "type": "none",
    "date": "2018-07-14T19:49:05.485467+00:00",
    "text": ""
}

**Comment by jkarneges** [comment]
Yes, GRIP_URL is not required to simply run the server. But, you'll need to set it for the realtime updates to work.
